### ISSUE TITLE
API key needed

### ISSUE THREAD

**Issue by yian-yin** [CrossRef/reference-matching-evaluation#1]
Hi, 

I am trying to run the draw_sample, yet I find the following erros:

FileNotFoundError: [Errno 2] No such file or directory: '/home/.crapi_key'

Does this mean I need something like an API key to get it run? Thanks.

**Comment by dtkaczyk** [comment]
Hi @yian-yin, thanks for reporting.

.crapi_key file can be used to provide your basic contact information (email address). It will be then passed to [Crossref REST API](https://github.com/CrossRef/rest-api-doc), whenever it is called by the script. This is optional, but strongly encouraged. Thanks to this, your requests will be handled by a more reliable pool of servers. You can read more about this feature [here](https://github.com/CrossRef/rest-api-doc#etiquette).

If you decide to use this feature, simply copy the file .crapi_key_example into .crapi_key in your home directory and fill in mailto and user-agent there. I also updated the README with this information.

However, if you decide to stay anonymous, you should be able to do so from now on. I removed the need to have .crapi_key, it is optional now.
